export enum OrderStatusCode {
  OPEN = 'OPEN',
  PREPARING = 'PREPARING',
  COMPLETED_DISH = 'COMPLETED_DISH',
  COMPLETED_ORDER = 'COMPLETED_ORDER',
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  PAYMENT_REVIEW = 'PAYMENT_REVIEW',
  CANCELED = 'CANCELED',
  CLOSED = 'CLOSED'
}
